### ISSUE TITLE
请问一下这个导航源码分享吗

### ISSUE THREAD

**Issue by kkkouo** [TactfulBean/BeansNav#7]
请问一下这个导航源码分享吗

**Comment by TactfulBean** [comment]
当然，如果需要二次开发里面的部分路径可能要换成你自己的

**Comment by kkkouo** [comment]
> 当然，如果需要二次开发里面的部分路径可能要换成你自己的

请问一下，这个能部署到GitHub上吗，会做成html这种吗

**Comment by TactfulBean** [comment]
> > 当然，如果需要二次开发里面的部分路径可能要换成你自己的
> 
> 请问一下，这个能部署到GitHub上吗，会做成html这种吗

可以，不过你要自己本地构建或者找自动部署的方法
