### ISSUE TITLE
请问一下大佬这个都需要修改哪些文件的路径呀

### ISSUE THREAD

**Issue by kkkouo** [TactfulBean/BeansNav#9]
本地部署后文件太多了，请问一下都需要修改哪个文件里的路径，才能改成自己的哈·感谢

**Comment by TactfulBean** [comment]
.env文件里有VITE_LINKBOX路径，这个是底下的网站链接，还有VITE_UPDATELOG，这个是右上角程序的更新日志，你也可以完全注释禁用掉更新日志这个功能

**Comment by GH-wudi** [comment]
> 本地部署后文件太多了，请问一下都需要修改哪个文件里的路径，才能改成自己的哈·感谢
建议学习下vue再来弄项目
